[package]
name = "sp-auth"
version = "0.1.0"
authors = ["Maximb <sprayrules@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

log = "*"
base64 = "*"
serde_json = "*"
hmac = "*"
sha3 = "*"